http://localhost:8080
#https://somind.tech
#https://somind.org

Content-Type: application/json; charset=utf-8

Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im5SMnhud2c1RDBBVWN2SXUyNjdFdiJ9.eyJpc3MiOiJodHRwczovL2F1dGguc29taW5kLnRlY2gvIiwic3ViIjoiZ2l0aHVifDExMDk5OSIsImF1ZCI6WyJodHRwczovL3NvbWluZC50ZWNoL2R0bGFiL2FkbWluIiwiaHR0cHM6Ly9uYXZpY29yZS51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNTk1MTY0OTc4LCJleHAiOjE1OTUyNTEzNzgsImF6cCI6IllaNzdVZnQ3aHZ3TzdkejdmMzZXaHlZMDBraG9VRzNhIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInBlcm1pc3Npb25zIjpbInJlYWQ6dHlwZSIsIndyaXRlOnR5cGUiXX0.Z1x-XcYRzwwxowFFzelVYsgVXdusZVV1ie4KaZm_f2q4eG2Pk1EWyl2BLsNOC3eibsGjmhfGdHU8qV5w1cNVymcSar2Z55lDT6jrmAXgZx0t1YtM033hohOAMTPwUJt_JPJ3vya449IkFIQJO5hTU2o0LIlzneC7rFF6QXKXPqY7WN8Ocffs_HDiaRyDvbqo9AGLrCD7QMH3XMHsuESDo_JM7cEx8Vj2gtjWvJhPRQ_QGSmgiVRN3hr3duC2UK67nWbxj2PVmcQ3G8LjqeRnhfRBZfpePhIUZdm76tg8AyKT672zVLL_Ln3IOv4oDkHDKjFT6Q04h8C8hznjdjC2hA


--

--
GET /api/type/machinery

--
GET /api/actor/machinery/one

--
GET /api/actor/badmachine/one/badmodule/2

--
GET /api/actor/machine/one/module/2/submodule/three

--
POST /api/actor/badmachine/one/badmodule/2/
{
  "idx": 0,
  "value": 2.1,
  "datetime": "2020-09-13T15:31:21.671Z"
}

--
POST /api/actor/machinery/one
{
  "idx": 0,
  "value": 5.5
}

--
GET /fitness

--
GET /observe

